name: Deploy

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  FORCED_KORGE_PLUGINS_VERSION: ${{ github.ref }}
  BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
  BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: chmod +x gradlew
      - run: ./gradlew check
      - run: ./gradlew publish

  publishVersionNumbers:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Get repository name
        run:  echo "::set-env name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')"

      - name: Get version
        run:  echo "::set-env name=VERSION::${GITHUB_REF/refs\/tags\/v/}"

      - name: Checkout korlibs-versions repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.KORGEBOT_TOKEN }}
          repository: korlibs/korlibs-versions

      - name: Bump version numbers
        run: |
          sed -i 's/'$REPOSITORY_NAME'Version=.*/'$REPOSITORY_NAME'Version='$VERSION'/g' versions.ver
          git config --global user.email "githubactionsbot@korge.org"
          git config --global user.name "korgebot"
          git add versions.ver
          git commit -m "${{ env.REPOSITORY_NAME }} bump to ${{ env.VERSION }}" -m "Bumped ${{ env.REPOSITORY_NAME }} version number to ${{ env.VERSION }}"
          git push
